package org.thcic.xapx.domain;

import java.util.Date;

/**
 * Equipment generated by MyEclipse Persistence Tools
 */

public class Equipment implements java.io.Serializable {
	// Fields
	private static final long serialVersionUID = 2513425736799661028L;
	private Long eqSeq;
	private CodeEqType codeEqType;
	private CodeEqStatus codeEqStatus;
	private String eqId;
	private String model;
	private Long quantity;
	private String weight;
	private String personResp;
	private Date dateModified;
	private String personModified;

	// Constructors

	/** default constructor */
	public Equipment() {
	}

	/** minimal constructor */
	public Equipment(Long eqSeq) {
		this.eqSeq = eqSeq;
	}

	/** full constructor */
	public Equipment(Long eqSeq, CodeEqType codeEqType,
			CodeEqStatus codeEqStatus, String eqId, String model,
			Long quantity, String weight, String personResp, Date dateModified,
			String personModified) {
		this.eqSeq = eqSeq;
		this.codeEqType = codeEqType;
		this.codeEqStatus = codeEqStatus;
		this.eqId = eqId;
		this.model = model;
		this.quantity = quantity;
		this.weight = weight;
		this.personResp = personResp;
		this.dateModified = dateModified;
		this.personModified = personModified;
	}

	// Property accessors

	public Long getEqSeq() {
		return this.eqSeq;
	}

	public void setEqSeq(Long eqSeq) {
		this.eqSeq = eqSeq;
	}

	public CodeEqType getCodeEqType() {
		return this.codeEqType;
	}

	public void setCodeEqType(CodeEqType codeEqType) {
		this.codeEqType = codeEqType;
	}

	public CodeEqStatus getCodeEqStatus() {
		return this.codeEqStatus;
	}

	public void setCodeEqStatus(CodeEqStatus codeEqStatus) {
		this.codeEqStatus = codeEqStatus;
	}

	public String getEqId() {
		return this.eqId;
	}

	public void setEqId(String eqId) {
		this.eqId = eqId;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public Long getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Long quantity) {
		this.quantity = quantity;
	}

	public String getWeight() {
		return this.weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	public String getPersonResp() {
		return this.personResp;
	}

	public void setPersonResp(String personResp) {
		this.personResp = personResp;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public String getPersonModified() {
		return this.personModified;
	}

	public void setPersonModified(String personModified) {
		this.personModified = personModified;
	}

}