/*
 * JSP generated by Resin-3.0.28 (built Mon, 18 May 2009 02:16:38 PDT)
 */

package _jsp._web_22dinf._view;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import org.thcic.xapx.Constants;

public class _login__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    com.caucho.jstl.rt.CoreUrlTag _jsp_CoreUrlTag_0 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      if (_jsp_CoreUrlTag_0 == null) {
        _jsp_CoreUrlTag_0 = new com.caucho.jstl.rt.CoreUrlTag();
        _jsp_CoreUrlTag_0.setPageContext(pageContext);
        _jsp_CoreUrlTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_CoreUrlTag_0.setValue("/j_spring_security_check");
      }

      _jsp_CoreUrlTag_0.doStartTag();
      _jsp_CoreUrlTag_0.doEndTag();
      out.write(_jsp_string1, 0, _jsp_string1.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_CoreUrlTag_0 != null)
        _jsp_CoreUrlTag_0.release();
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -4644494061398360982L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/view/login.jsp"), 7443925450786687781L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("D:/XianProject/resin-3.0.28/lib/resin.jar"), 3420069261137021765L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(com.caucho.jstl.rt.CoreUrlTag.class, -305958705870469798L));
  }

  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  static {
    _jsp_string0 = "\r\n\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\">\r\n<head>\r\n	<meta http-equiv=\"Content-Type\" content=\"text/html;charset=UTF-8\" />\r\n	<title>\u519b\u4e8b\u88c5\u5907\u7ba1\u7406\u7cfb\u7edf</title>\r\n	<link href=\"/res/styles/common.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n	<link href=\"/res/styles/login.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n</head>\r\n<body>\r\n				<form id=\"loginForm\"\r\n					action=\"".toCharArray();
    _jsp_string1 = "\" method='POST'>\r\n	<div id=\"login\">\r\n		<div class=\"login_c\">\r\n			<div class=\"login_box\">\r\n				<div class=\"login_inner\">\r\n					<h1>\u519b\u4e8b\u88c5\u5907\u7ba1\u7406\u7cfb\u7edf</h1>\r\n					<div class=\"login_wrap\">\r\n						<table width=\"80%\">\r\n							<tr height=\"40\">\r\n								<td width=\"20%\"><span class=\"login_txt\">\u7528\u6237\u540d</span></td>\r\n								<td><input type=\"text\" name=\"j_username\"  class=\"login_input\" /></td>\r\n							</tr>\r\n							<tr height=\"40\">\r\n								<td><span class=\"login_txt\">\u5bc6&nbsp;&nbsp;&nbsp;&nbsp;\u7801</span></td>\r\n								<td><input type=\"password\" name=\"j_password\" class=\"login_input\" /></td>\r\n							</tr>\r\n							<tr height=\"40\">\r\n								<td></td>\r\n								<td>\r\n									<table>\r\n										<tr>\r\n											<td>\r\n												<input type=\"submit\" value=\"\u767b\u5f55\" class=\"login_btn\" />\r\n												<input type=\"reset\" class=\"login_btn\" />\r\n											</td>\r\n										</tr>\r\n									</table>\r\n								</td>\r\n							</tr>\r\n						</table>\r\n						<img src=\"/res/images/star_19.png\" alt=\"\" class=\"star\" />\r\n					</div>\r\n				</div>\r\n				<div class=\"decoration\"></div>\r\n			</div>\r\n		</div>\r\n	</div>\r\n</form>\r\n</body>\r\n</html>\r\n".toCharArray();
  }
}
